version: "3.9"
services:
  training:
    build:
      dockerfile: Dockerfile.training
    volumes:
      - "./training:/code/training"
  svc:
    restart: unless-stopped
    build:
      dockerfile: Dockerfile.bot
